package net.kogasachan.upgradedbread.datagen;

import net.kogasachan.upgradedbread.block.BreadBlocks;
import net.kogasachan.upgradedbread.item.BreadItems;
import net.minecraft.advancements.critereon.ItemPredicate;
import net.minecraft.data.PackOutput;
import net.minecraft.data.recipes.*;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Ingredient;
import org.jetbrains.annotations.NotNull;

import java.util.function.Consumer;

public class BreadRecipeProvider extends RecipeProvider {
    // 配方
    public BreadRecipeProvider(PackOutput pOutput) {
        super(pOutput);
    }

    @Override
    protected void buildRecipes(@NotNull Consumer<FinishedRecipe> pWriter) {
        final String SMELT_TAIL = "_from_smelting";
        final String SMOKE_TAIL = "_from_smoking";
        final String CAMP_TAIL = "_from_campfire_cooking";
        final String ESSENCE_TAIL = "_from_essence";

        // Shaped
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.BLAZE_GROUP.get(), 3)
                .define('M', Items.BLAZE_POWDER)
                .define('N', Items.NETHER_WART)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EME")
                .pattern("NEN")
                .pattern("EME")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.BREATHE_ESSENCE.get(), 8)
                .define('P', BreadItems.PUFF_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.BREATHE_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.BREATHE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_breathe", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.BREATHE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.CARBOHYDRATE_INGOT.get(), 1)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter, getItemName(BreadItems.CARBOHYDRATE_INGOT.get()) + ESSENCE_TAIL);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.CARROT_GROUP.get(), 3)
                .define('M', Items.GOLDEN_CARROT)
                .define('N', Items.NETHER_WART)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EME")
                .pattern("NEN")
                .pattern("EME")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.DECAYED_GROUP.get(), 3)
                .define('M', Items.FERMENTED_SPIDER_EYE)
                .define('N', Items.NETHER_WART)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EME")
                .pattern("NEN")
                .pattern("EME")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.EMERALD_GROUP.get(), 1)
                .define('M', Items.EMERALD_BLOCK)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EME")
                .pattern("MEM")
                .pattern("EME")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.FIRE_RESISTANCE_ESSENCE.get(), 8)
                .define('P', BreadItems.MAGMA_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.FIRE_RESISTANCE_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.FIRE_RESISTANCE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_fire_resistance", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.FIRE_RESISTANCE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.FISHING_GROUP.get(), 1)
                .define('A', Items.COD)
                .define('B', Items.SALMON)
                .define('N', Items.NETHER_WART_BLOCK)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EAE")
                .pattern("BNB")
                .pattern("EAE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.FISHING_ESSENCE.get(), 8)
                .define('P', BreadItems.FISHING_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.FISHING_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.FISHING_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_fishing", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.FISHING_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.FOOT_GROUP.get(), 3)
                .define('M', Items.RABBIT_FOOT)
                .define('N', Items.NETHER_WART)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EME")
                .pattern("NEN")
                .pattern("EME")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.FRESH_LONG_BREAD.get(), 1)
                .define('#', Items.BREAD)
                .pattern("  #")
                .pattern(" # ")
                .pattern("#  ")
                .unlockedBy("has_bread", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(Items.BREAD).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.GREED_ESSENCE.get(), 8)
                .define('P', BreadItems.GREED_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.GREED_GROUP.get(), 1)
                .define('A', BreadItems.BLAZE_GROUP.get())
                .define('B', BreadItems.CARROT_GROUP.get())
                .define('N', Items.NETHER_WART_BLOCK)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EAE")
                .pattern("BNB")
                .pattern("EAE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.GREED_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.GREED_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_greed", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.GREED_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.HARD_BREAD.get(), 1)
                .define('#', Items.BREAD)
                .pattern("#")
                .pattern("#")
                .pattern("#")
                .unlockedBy("has_bread", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(Items.BREAD).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.HARDER_BREAD.get(), 1)
                .define('#', BreadItems.HARD_BREAD.get())
                .pattern("#")
                .pattern("#")
                .pattern("#")
                .unlockedBy("has_hard_bread", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(Items.BREAD).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.HEALTH_ESSENCE.get(), 8)
                .define('P', BreadItems.MELON_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.HEALTH_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.HEALTH_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_health", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.HEALTH_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.HEART_OF_THE_COAL.get(), 1)
                .define('C', Ingredient.of(Items.COAL, Items.CHARCOAL))
                .define('B', Items.BONE_MEAL)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("CBC")
                .pattern("BEB")
                .pattern("CBC")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.HIGH_ENERGY_CORE.get(), 1)
                .define('C', Ingredient.of(Items.COAL, Items.CHARCOAL))
                .define('L', BreadItems.LOST_ENERGY_CORE.get())
                .pattern("CCC")
                .pattern("CLC")
                .pattern("CCC")
                .unlockedBy("has_lost_core", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.LOST_ENERGY_CORE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.INFLUENCE_ESSENCE.get(), 8)
                .define('P', BreadItems.INFLUENCE_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.INFLUENCE_GROUP.get(), 1)
                .define('A', BreadItems.EMERALD_GROUP.get())
                .define('B', Items.TOTEM_OF_UNDYING)
                .define('N', Items.NETHER_WART_BLOCK)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("ENE")
                .pattern("ABA")
                .pattern("ENE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.INFLUENCE_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.INFLUENCE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_influence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.INFLUENCE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.INVISIBILITY_ESSENCE.get(), 8)
                .define('P', BreadItems.DECAYED_GROUP.get())
                .define('E', BreadItems.NIGHT_VISION_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_night_vision", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.NIGHT_VISION_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.INVISIBILITY_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.INVISIBILITY_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_invisibility", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.INVISIBILITY_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.JUMP_BOOST_ESSENCE.get(), 8)
                .define('P', BreadItems.FOOT_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.JUMP_BOOST_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.JUMP_BOOST_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_jump_boost", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.JUMP_BOOST_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.MAGMA_GROUP.get(), 3)
                .define('M', Items.MAGMA_CREAM)
                .define('N', Items.NETHER_WART)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EME")
                .pattern("NEN")
                .pattern("EME")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.MELON_GROUP.get(), 3)
                .define('M', Items.GLISTERING_MELON_SLICE)
                .define('N', Items.NETHER_WART)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EME")
                .pattern("NEN")
                .pattern("EME")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.MEMBRANE_GROUP.get(), 3)
                .define('M', Items.PHANTOM_MEMBRANE)
                .define('N', Items.NETHER_WART)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EME")
                .pattern("NEN")
                .pattern("EME")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.NIGHT_VISION_ESSENCE.get(), 8)
                .define('P', BreadItems.CARROT_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.NIGHT_VISION_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.NIGHT_VISION_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_night_vision", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.NIGHT_VISION_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.PUFF_GROUP.get(), 3)
                .define('M', Items.PUFFERFISH)
                .define('N', Items.NETHER_WART)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EME")
                .pattern("NEN")
                .pattern("EME")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.REGENERATION_ESSENCE.get(), 8)
                .define('P', BreadItems.TEAR_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.REGENERATION_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.REGENERATION_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_regeneration", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.REGENERATION_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.SLOW_FALLING_ESSENCE.get(), 8)
                .define('P', BreadItems.MEMBRANE_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.SLOW_FALLING_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.SLOW_FALLING_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_slow_falling", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.SLOW_FALLING_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.SPEED_ESSENCE.get(), 8)
                .define('P', BreadItems.SUGAR_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.SPEED_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.SPEED_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_speed", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.SPEED_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.STRENGTH_ESSENCE.get(), 8)
                .define('P', BreadItems.BLAZE_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.STRENGTH_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.STRENGTH_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_strength", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.STRENGTH_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.SUGAR_GROUP.get(), 3)
                .define('M', Items.SUGAR)
                .define('N', Items.NETHER_WART)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EME")
                .pattern("NEN")
                .pattern("EME")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.TEAR_GROUP.get(), 3)
                .define('M', Items.GHAST_TEAR)
                .define('N', Items.NETHER_WART)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EME")
                .pattern("NEN")
                .pattern("EME")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Items.WHEAT, 8)
                .define('S', Items.WHEAT_SEEDS)
                .define('C', Ingredient.of(BreadItems.HIGH_ENERGY_CORE.get(), BreadItems.LOW_ENERGY_CORE.get()))
                .pattern("SSS")
                .pattern("SCS")
                .pattern("SSS")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.FREEZING_GROUP.get(), 1)
                .define('A', Items.BLUE_ICE)
                .define('B', Items.PACKED_ICE)
                .define('N', Items.NETHER_WART_BLOCK)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EAE")
                .pattern("BNB")
                .pattern("EAE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.FREEZING_ESSENCE.get(), 8)
                .define('P', BreadItems.FREEZING_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.FREEZING_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.FREEZING_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_freezing", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.FREEZING_ESSENCE.get()).build()))
                .save(pWriter);

        // Shaped (new)
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.BONE_MEAL_GROUP.get(), 1)
                .define('A', Items.BONE_MEAL)
                .define('N', Items.DIRT)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EAE")
                .pattern("ANA")
                .pattern("EAE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.GROWTH_ESSENCE.get(), 8)
                .define('P', BreadItems.BONE_MEAL_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.KE_LA_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.GROWTH_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_bone_meal", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.FREEZING_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.TOTEM_GROUP.get(), 1)
                .define('A', Items.TOTEM_OF_UNDYING)
                .define('N', Items.GOLD_BLOCK)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EAE")
                .pattern("ANA")
                .pattern("EAE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.LIFE_ESSENCE.get(), 8)
                .define('P', BreadItems.TOTEM_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.LEES_WAFFLE.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.LIFE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_totem", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.LEES_WAFFLE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.COCOA_GROUP.get(), 1)
                .define('A', Items.COCOA_BEANS)
                .define('B', Items.SUGAR)
                .define('N', Items.BLUE_ICE)
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EAE")
                .pattern("BNB")
                .pattern("EAE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.CHOCLIZ_ESSENCE.get(), 8)
                .define('P', BreadItems.COCOA_GROUP.get())
                .define('E', BreadItems.CARBOHYDRATE_ESSENCE.get())
                .pattern("EEE")
                .pattern("EPE")
                .pattern("EEE")
                .unlockedBy("has_essence", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CARBOHYDRATE_ESSENCE.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.CHOCLIZ_LONG_BREAD.get(), 1)
                .define('B', BreadItems.FRESH_LONG_BREAD.get())
                .define('E', BreadItems.CHOCLIZ_ESSENCE.get())
                .pattern("EEE")
                .pattern("EBE")
                .pattern("EEE")
                .unlockedBy("has_chocliz", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.CHOCLIZ_LONG_BREAD.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.BAGUETTE_BAGUETTE.get(), 1)
                .define('#', BreadItems.FRESH_LONG_BREAD.get())
                .pattern("  #")
                .pattern(" # ")
                .pattern("#  ")
                .unlockedBy("has_long_bread", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.FRESH_LONG_BREAD.get()).build()))
                .save(pWriter);
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Items.BREAD, 1)
                .define('#', BreadItems.MICRO_SOFT_BREAD.get())
                .pattern("##")
                .pattern("##")
                .unlockedBy("has_bread", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(Items.BREAD).build()))
                .save(pWriter, "bread_from_micro_soft_bread");
        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BreadItems.MACRO_HARD_BREAD.get(), 1)
                .define('#', BreadItems.FRESH_LONG_BREAD.get())
                .pattern("##")
                .pattern("##")
                .unlockedBy("has_long_bread", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.FRESH_LONG_BREAD.get()).build()))
                .save(pWriter);

        // Shapeless
        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, Items.BREAD, 3)
                .requires(BreadItems.FRESH_LONG_BREAD.get())
                .unlockedBy("has_long_bread", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.FRESH_LONG_BREAD.get()).build()))
                .save(pWriter);
        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, BreadItems.LOW_ENERGY_CORE.get(), 1)
                .requires(BreadItems.LOST_ENERGY_CORE.get(), 8)
                .unlockedBy("has_lost_core", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.LOST_ENERGY_CORE.get()).build()))
                .save(pWriter);

        // Shapeless (new)
        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, BreadItems.MICRO_SOFT_BREAD.get(), 4)
                .requires(Items.BREAD)
                .unlockedBy("has_bread", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(Items.BREAD).build()))
                .save(pWriter);
        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, BreadItems.FRESH_LONG_BREAD.get(), 4)
                .requires(BreadItems.MACRO_HARD_BREAD.get())
                .unlockedBy("has_long_bread", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.FRESH_LONG_BREAD.get()).build()))
                .save(pWriter, "fresh_long_bread_from_macro_hard_bread");

        // nineBlockStorage
        nineBlockStorageRecipes(pWriter,
                RecipeCategory.MISC,
                BreadItems.CARBOHYDRATE_INGOT.get(),
                RecipeCategory.MISC,
                BreadBlocks.CARBOHYDRATE_BLOCK_ITEM.get());

        // SimpleCook
        SimpleCookingRecipeBuilder.smelting(Ingredient.of(BreadItems.HARDER_BREAD.get()),
                        RecipeCategory.MISC,
                        BreadItems.CARBOHYDRATE_ESSENCE.get(), 1.0F, 200)
                .unlockedBy("has_harder_bread", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.HARDER_BREAD.get()).build()))
                .save(pWriter);
        SimpleCookingRecipeBuilder.smoking(Ingredient.of(BreadItems.HARDER_BREAD.get()),
                        RecipeCategory.MISC,
                        BreadItems.CARBOHYDRATE_ESSENCE.get(), 1.0F, 100)
                .unlockedBy("has_harder_bread", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.HARDER_BREAD.get()).build()))
                .save(pWriter, getItemName(BreadItems.CARBOHYDRATE_ESSENCE.get()) + SMOKE_TAIL);
        SimpleCookingRecipeBuilder.campfireCooking(Ingredient.of(BreadItems.HARDER_BREAD.get()),
                        RecipeCategory.MISC,
                        BreadItems.CARBOHYDRATE_ESSENCE.get(), 1.0F, 600)
                .unlockedBy("has_harder_bread", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.HARDER_BREAD.get()).build()))
                .save(pWriter, getItemName(BreadItems.CARBOHYDRATE_ESSENCE.get()) + CAMP_TAIL);

        SimpleCookingRecipeBuilder.smelting(Ingredient.of(BreadItems.FRESH_LONG_BREAD.get()),
                        RecipeCategory.MISC,
                        BreadItems.DRY_LONG_BREAD.get(), 1.05F, 200)
                .unlockedBy("has_fresh_long_bread", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.FRESH_LONG_BREAD.get()).build()))
                .save(pWriter);
        SimpleCookingRecipeBuilder.smoking(Ingredient.of(BreadItems.FRESH_LONG_BREAD.get()),
                        RecipeCategory.MISC,
                        BreadItems.DRY_LONG_BREAD.get(), 1.05F, 100)
                .unlockedBy("has_fresh_long_bread", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.FRESH_LONG_BREAD.get()).build()))
                .save(pWriter, getItemName(BreadItems.DRY_LONG_BREAD.get()) + SMOKE_TAIL);
        SimpleCookingRecipeBuilder.campfireCooking(Ingredient.of(BreadItems.FRESH_LONG_BREAD.get()),
                        RecipeCategory.MISC,
                        BreadItems.DRY_LONG_BREAD.get(), 1.05F, 600)
                .unlockedBy("has_fresh_long_bread", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.FRESH_LONG_BREAD.get()).build()))
                .save(pWriter, getItemName(BreadItems.DRY_LONG_BREAD.get()) + CAMP_TAIL);

        SimpleCookingRecipeBuilder.smelting(Ingredient.of(BreadItems.HEART_OF_THE_COAL.get()),
                        RecipeCategory.MISC,
                        BreadItems.LOW_ENERGY_CORE.get(), 0.5F, 200)
                .unlockedBy("has_heart_of_the_coal", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.HEART_OF_THE_COAL.get()).build()))
                .save(pWriter, getItemName(BreadItems.LOW_ENERGY_CORE.get()) + SMELT_TAIL);
        SimpleCookingRecipeBuilder.smoking(Ingredient.of(BreadItems.HEART_OF_THE_COAL.get()),
                        RecipeCategory.MISC,
                        BreadItems.LOW_ENERGY_CORE.get(), 0.5F, 100)
                .unlockedBy("has_heart_of_the_coal", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.HEART_OF_THE_COAL.get()).build()))
                .save(pWriter, getItemName(BreadItems.LOW_ENERGY_CORE.get()) + SMOKE_TAIL);
        SimpleCookingRecipeBuilder.campfireCooking(Ingredient.of(BreadItems.HEART_OF_THE_COAL.get()),
                        RecipeCategory.MISC,
                        BreadItems.LOW_ENERGY_CORE.get(), 0.5F, 600)
                .unlockedBy("has_heart_of_the_coal", inventoryTrigger(ItemPredicate.Builder.item()
                        .of(BreadItems.HEART_OF_THE_COAL.get()).build()))
                .save(pWriter, getItemName(BreadItems.LOW_ENERGY_CORE.get()) + CAMP_TAIL);
    }
}
